задачи по стримам
js-tasks-ru/nodejs-20201020_vladimir-zaytsev pull request #7
Opened 2020-11-03 18:55 UTC by writer2159

Правка ошибки отсутствия файла в отдаче файла
сделан прием файла
сделано удаление файла

2020-11-03 19:59 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ при попытке создания слишком большого файла - ошибка 413
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - удаление файла
+ файл должен удаляться
+ если файла нет - ошибка 404
+ если путь вложенный - возвращается ошибка 400
```

Добавляю преподавателя (@tadjik1) для код-ревью, посмотрим что он скажет :)

2020-11-04 07:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-04 07:58 UTC, tadjik1 commented on 06-koajs/01-chat-app/app.js
> +
Нужно еще очищать набор сабскрайберов после перебора, можно операцией `storageSubscribes .clear()`. Иначе они будут накапливаться (несмотря на то, что сами запросы будут завершаться, множество объектов останутся в памяти.

2020-11-04 07:59 UTC, tadjik1 requested changes
@writer2159 решения отличные! оставил небольшой комментарий по поводу очистки сабсрайберов, в остальном всё абсолютно правильно!

2020-11-04 10:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2020-11-04 11:00 UTC, tadjik1 approved these changes
отлично! 🥇

2020-11-04 11:01 UTC, merged